# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXPbINVaeoTvgvmLtYwrhNEiWnsHHFHt
"""

import pandas as pd, tensorflow as tf
from tensorflow.keras.layers import TextVectorization


df = pd.read_csv("spam.csv", encoding="latin-1")[["v1","v2"]]
y = (df.v1 == "spam").astype("int32").values
x = df.v2.values


vec = TextVectorization(max_tokens=5000, output_mode="int", output_sequence_length=20)
vec.adapt(x)
x_vec = vec(x)

# basic model
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(5000, 8),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(1, activation="sigmoid")
])

model.compile("adam", "binary_crossentropy", metrics=["accuracy"])
model.fit(x_vec, y, epochs=10, batch_size=32, verbose=0)

# accuracy
loss, acc = model.evaluate(x_vec, y, verbose=0)
print("Accuracy:", acc)

# sample prediction
msg = ["You are a winner U have been specially selected to win big!!"]
p = model.predict(vec(msg), verbose=0)[0][0]
print("Spam probability:", p)
print("Prediction:", "SPAM" if p >= 0.5 else "HAM")

